const ODL_URL_BASE = "http://";
const ODL_PORT = ":8181/"
const ODL_RESTCONF_CONFIG = "restconf/config/"
const ODL_RESTCONF_OPERATIONS = "restconf/operations/"
const ODL_RESTCONF_OPERATIONAL = "restconf/operational/"

module.exports = {
    ODL_URL_BASE: ODL_URL_BASE,
    ODL_PORT: ODL_PORT,
    ODL_RESTCONF_CONFIG: ODL_RESTCONF_CONFIG,
    ODL_RESTCONF_OPERATIONS: ODL_RESTCONF_OPERATIONS,
    ODL_RESTCONF_OPERATIONAL: ODL_RESTCONF_OPERATIONAL
};

