const UC_URL_BASE = "http://";
const UC_PORT = ":8181/"
const UC_RESTCONF_CONFIG = "rests/data/"
const UC_RESTCONF_OPERATIONS = "rests/data/"
const UC_RESTCONF_OPERATIONAL = "rests/data/"
const DEFAULT_DELIMITER = "frinxit"

module.exports = {
    UC_URL_BASE: UC_URL_BASE,
    UC_PORT: UC_PORT,
    UC_RESTCONF_CONFIG: UC_RESTCONF_CONFIG,
    UC_RESTCONF_OPERATIONS: UC_RESTCONF_OPERATIONS,
    UC_RESTCONF_OPERATIONAL: UC_RESTCONF_OPERATIONAL,
    DEFAULT_DELIMITER: DEFAULT_DELIMITER
}


